fido-device-onboard/client-sdk-fidoiot

- CMakeLists.txt
- Jenkinsfile.yml
- lib/CMakeLists.txt
- lib/credentials_from_file.c
- lib/include/sdoblockio.h
- lib/include/sdoprot.h
- lib/m-string.c
- lib/sdo.c
- lib/sdoblockio.c
- lib/sdocred.c
- lib/sdoprot.c
- lib/sdoprotctx.c
- lib/sdotypes.c
- tests/unit/CMakeLists.txt
- tests/unit/test_sdoblockio.c
- tests/unit/test_sdotypes.c
- Integrated TinyCBOR to be used as the CBOR encoder/decoder.
- Updated SdoBlockio to use TinyCBOR to encode/decode messages
to-and-fro CBOR. The structures have been updated to use
CborEncoder/CborValue and it resembles a Doubly-linked-list to chain
the TinyCBOR's CborEncoder and CborValue structures.
Additionally, added a Unit-test for the same.
- Updated the lib/*.c classes to remove the old methods. Also, excluded
the lib/prot/*.c from compilation for now. The implementation for
changes will happen during FIDOIOT Protocol Spec's
implementation. TO-DO comments have been added for the same at multiple
places. Excluded the same classes from the test cases.
> Initial CBOR Encoder/Decoder structure

- lib/CMakeLists.txt
- lib/include/sdoprot.h
- lib/include/sdotypes.h
- lib/m-string.c
- lib/prot/to1/msg30.c
- lib/prot/to1/msg31.c
- lib/prot/to1/msg32.c
- lib/prot/to1/msg33.c
- lib/sdo.c
- lib/sdocred.c
- lib/sdoprot.c
- lib/sdoprotctx.c
- lib/sdotypes.c
- Updating TO1 protocol messages (30-33) as per the FDO spec.
As a part of implementation, read and write operations for COSE and EAT
structures have been added, along with RVTO2Addr struct.
- RendezvousInfoList structure has been updated to contain RVDirectives
that inturn contain RVInstructions. This had been done so as to loop
through directives while trying for TO1.
- Fixing the DeviceMfgInfo flow for TPM, wherein, the TPM-generated CSR
was overwritten by file-system's EC-key generated CSR.
> Transfer Ownership (TO1) implementation in CBOR

- cmake/extension.cmake
- device_modules/sdo_sys/sdo_sys.c
- device_modules/sdo_sys/sdo_sys.h
- device_modules/sdo_sys/sdomodules.h
- device_modules/sdo_sys/sys_utils_linux.c
- include/sdomodules.h
- lib/include/sdodeviceinfo.h
- lib/include/sdotypes.h
- lib/prot/to2/msg48.c
- lib/prot/to2/msg49.c
- lib/sdo.c
- lib/sdotypes.c
- The current sdo_sys module and supporting methods have been updated to
work with CBOR. The module now takes in the CBOR stream directly,
processes the currently pointed-at ServiceInfoVal and returns, instead
of the older approach where key-value pairs were provided. This is
because only the ServiceInfo module knows how to parse the
ServiceInfoVal now, as opposed to being known Base-64 encoded value
previously. It also has been updated to being an Owner ServiceInfo
processing module only.
- The Device ServiceInfo only has the mandatory 'devmod' module added.
Support for multiple Device ServiceInfo modules will be added at a later
time.
> ServiceInfo implementation for sdo_sys module

- lib/include/sdotypes.h
- lib/sdo.c
- lib/sdoprotctx.c
- lib/sdotypes.c
- network/network_if_linux.c
- network/network_if_mbedos.c
Fixing a couple of issues with RVBypass and TO2 TLS:
- Fixing the RVBYPASS flow and updating the bool structure being used for
it. Subsequently, the bool wrapper struct has been removed.
- Fixing an issue where TO2 was not starting with TLS in RVBYPASS flow
when its been specified in RendezvousInfo by passing the TLS flag when
found. However, this fixes the TO2 TLS flow for RVTO2Addr as well.
> Fix for issues in rvbypass and TO2 TLS flow

- app/main.c
- cmake/blob_path.cmake
- device_modules/fdo_sys/fdo_sys.c
- device_modules/fdo_sys/fdo_sys.h
- device_modules/fdo_sys/sys_utils_linux.c
- lib/fdo.c
- lib/fdotypes.c
- lib/include/fdoprot.h
- lib/include/fdotypes.h
- lib/prot/to2/msg66.c
- lib/prot/to2/msg67.c
- lib/prot/to2/msg68.c
- lib/prot/to2/msg69.c
- Replaced the existing sdo_sys Owner ServiceInfo module implementation
to fdo_sys.
- Updated devmod:modules to align with FDO spec and moved it to
fdo_types.c
- Added support for configurable MTU by allowing the user to decide the
maximum ServiceInfo size that the device can support, by updating a file
data/max_serviceinfo_sz. This inturn, decides the size of the buffer
being allocated for protocol-specific messages.
- Added a flag to track  TO2.DeviceServiceInfo.IsMoreServiceInfo that is
used to check in TO2.OwnerServiceInfo for empty ServiceInfo scenario.
- Fixed an issue where the ServiceInfo module iteration was done on the
primary pointer leading to 'module not found' error at certain
situations.
> Updates to serviceinfo and replace sdo_sys with fdo_sys

- lib/fdotypes.c
- lib/include/fdotypes.h
- lib/prot/to2/msg66.c
- Previously RendezvousInfo comparioson was limited to them being
non-null. Updated the code to compare RendezvousDirective and
RendezvousInstr within.
- In non-resale scenario, now returning CBOR NULL as replacementHmax,
instead of throwing error.
> Adding RendezvousInfo comparison and updating non-resale scenario

- lib/fdo.c
- lib/fdocred.c
- lib/fdoprotctx.c
- lib/fdotypes.c
- lib/include/fdoprot.h
- lib/prot/to1/msg32.c
- lib/prot/to2/msg61.c
- lib/prot/to2/msg64.c
Fixing the following issues:
- Fixing a sceario where 0 was returned instead of -1 on onboarding
failure.
- Fixing a scenario where buffer overflow was happening in case the
response message was more than the buffer size allocated. To accomodate
this, a new state variable has been created that stores the allocated
buffer size and is used throughout the application now.
- Fixing mememory leak in retry scenario for variable 'resolved_dns'.
- Updating Log level for 'Skipping TO1' message in case RVBYPASS is
encountered.
> Fixing few issues

- crypto/include/fdoCryptoHal.h
- crypto/mbedtls/mbedtls_ECDSAVerifyRoutines.c
- crypto/mbedtls/mbedtls_RSAVerifyRoutines.c
- crypto/openssl/openssl_ECDSAVerifyRoutines.c
- crypto/openssl/openssl_RSAVerifyRoutines.c
- crypto/se/se_ECDSAVerifyRoutines.c
- lib/include/fdotypes.h
- Update the used PublicKey.pkType constant for EC256 and EC284 key
types as FDO spec.
> Update Public key constants as per FDO spec

- lib/prot/to2/msg63.c
- Fix an issue where an OwnershipVoucher of size 2 or more was not going
through the Type 62-63 loop correctly, by clearing out the FDOW buffer.
> Fix processing of Ownership Voucher of size 2 or more

- lib/fdo.c
- lib/include/fdotypes.h
- Add constants as per Section 3.3.12 (Transport protocol) of FDO spec,
and replace the usage of RVProtocol value with these new constants while
invoking TO2.
> Replace TLS/HTTPS constants for RVTO2Addr

- lib/fdoblockio.c
- Added few more checks while parsing input CBOR stream at fdoblockio.c
that avoids Assert errors at TinyCBOR library.
> Add few more conditions for parsing input stream

- crypto/common/fdoKeyExchange.c
- crypto/openssl/openssl_key_exchange_ecdh.c
- lib/fdo.c
- lib/fdonet.c
- lib/fdotypes.c
- network/rest_interface.c
- Replaced atoi() usage with strtol() at places that are used currently.
Replacement in unused code will be done in further releases.
- Updated/Removed few debug logs.
> Replace atoi() with strtol() and update few debug logs

- device_modules/fdo_sys/fdo_sys.c
- device_modules/fdo_sys/sys_utils_linux.c
- The file name of the received ServiceInfo script to be executed as per
the fdo_sys:exec command, was being parsed to find the dot character (.)
in the first 10 characters of the file name. Updated it use the full
filename length.
- Adding a check for empty content received for value of
fdo_sys:filedesc (invalid scenario, fail immediately) and
fdo_sys:write (valid scenario).
> Fix for issues in ServiceInfo parsing

- tests/unit/CMakeLists.txt
- tests/unit/test_cryptoSupport.c
- tests/unit/test_cryptoUtils.c
- tests/unit/test_fdoblockio.c
- Certain unit-tests have been commented-out/disabled as they were
leading to compilation-failures/testcase-failures. The same will be
enabled back in future release when unit-tests are updated as per the
current implementation.
> Updating to fix unit-tests compliation failures

- tests/unit/test_credentials.c
> Close file pointer when error occurs in unit-test

- lib/include/util.h
Currently the filename is printed for LOG messages. The filename
contains the absolute path of the location of the current file in the
build system. This has the potential to leak some sensitive information
about the build system as part of the LOG messages.
Instead, passing the function name and the line number would provide
necessary information for debugging. This would also ensure that the LOG
messages would be same irrespective of the build system used.
Old error message:
ERROR:[/home/user/client-sdk-fidoiot/crypto/openssl/openssl_csr.c:138]
Failed to generate CSR data
New error message:
ERROR:[crypto_hal_get_device_csr():138] Failed to generate CSR data
> Change logging to use function name

- Jenkinsfile.yml
- build.sh
Update build system to remove unused flags and build for GCM/CCM
variants.
Also unify the build commands to a single function for easier
maintenance.
> Update build system

- crypto/ecdsa/ecdsa_privkey.c
- crypto/openssl/ec_key.c
When privkey is uninitialized, the behaviour of the function becomes
unpredictable in case of a failure to read the EC key. Initializing the
variables fixes the issue.
> Fix possible memory leak in get_ec_key

- cmake/blob_path.cmake
The MACRO required to enable PEM file support was not wired with cmake
build system.
> Fix support for PEM formatted key

- include/fdomodules.h
- lib/fdo.c
- lib/fdoprot.c
- lib/fdotypes.c
- lib/include/fdoprot.h
- lib/include/fdotypes.h
- lib/prot/to2/msg68.c
- lib/prot/to2/msg69.c
- tests/unit/test_fdotypes.c
- When Owner sends ServiceInfo instructions for an unsupported module,
the Device stores the module names in a list and responds back with the
following message when the Owner sends
TO2OwnerServiceInfo.ismoreServiceInfo as 'false':
ServiceInfo = [[[modname1:active, false],[modname2:active, false]..]]
where, modnameN is the received unsupported module name.
> Updating handling of unsupported ServiceInfo modules

- app/main.c
- lib/fdo.c
- lib/fdocred.c
- lib/fdotypes.c
- lib/include/fdocred.h
- lib/include/fdoprot.h
- lib/include/fdotypes.h
- lib/prot/to2/msg67.c
- lib/prot/to2/msg68.c
- Split the Device ServiceInfo (devmod + unsupported module list) based
on the MTU as specified by the Owner and supported by Device, and send
across multiple msg/68-69 iterations.
- The splitting is done by considering an additional margin for CBOR
encoding. The key-values are CBOR encoded once to decide how many
key-value pairs (partial/complete), can be fitted within the
current message as per MTU. Based on the findings, the ServiceInfo is
CBOR encoded again. This is done in this way, since the underlying
TinyCBOR library doesn't allow us to change the total number of entries
in an array (ServiceInfoKeyVal, in this case), once it's set. As result,
we find the total number of array entries first, by first round of CBOR
encoding + partial/complete key-value entries, and then do the 2nd …
> Update Device ServiceInfo processing and separate buffer size from MTU

- lib/fdo.c
- lib/fdoblockio.c
- lib/fdotypes.c
- Use fdow_signed_int(), instead of fdow_unsigned_int() while creating
SigInfo.
- Fix certain memory leaks that occur in DI/TO1/TO2 failures.
> Fix: Use signed int API for Siginfo and memory leaks

- crypto/openssl/tpm20_ECDSASignRoutines.c
- crypto/openssl/tpm20_Utils.c
- Add checks for return values of certain TPM library methods.
- Zeroise some local variables.
> Add checks and zeroise certain buffers in TPM

- lib/fdoblockio.c
- lib/fdotypes.c
- lib/include/fdoblockio.h
- lib/include/fdotypes.h
- tests/unit/test_fdotypes.c
- Previously, the COSE unprotected header map was being parsed in an
ordered manner (entry1, entry2 and so on..). Update the parsing to read
the same map for the same elemnts in an iterative, un-ordered manner.
The header is only supposed to either contain 0 or 2 specific entries.
For any unknown entry, parsing would return an error.
NOTE: Similar parsing be done for other maps as well. However, as of
now, they only contain 1 single entry. So these are being parsed in an
ordered manner (unchanged for now). If more elements need to be parsed,
then those would need to be updated.
- Additionally, fix certain commenting issues, add few NULL checks and
remove unnecessary cose-free being done.
> Fix COSE unprotected header parsing

- device_modules/fdo_sys/sys_utils_linux.c
- Allow the use of hyphen '-' in filename of the command received in
fdo_sys:exec.
- Checking the fdo_sys:exec command to return non-zero value for failure
and zero for success.
> Allow hyphens '-' in filenames and update command execution value

- cmake/blob_path.cmake
- crypto/common/fdoCryptoCommon.c
- crypto/common/fdoHmac.c
- crypto/include/fdoCrypto.h
- crypto/include/fdoCryptoCtx.h
- crypto/include/tpm20_Utils.h
- crypto/openssl/tpm20_Utils.c
- lib/fdo.c
- lib/fdocred.c
- lib/fdoprot.c
- lib/fdotypes.c
- lib/include/fdotypes.h
- lib/prot/to2/msg66.c
- lib/prot/to2/msg70.c
- tests/unit/test_cryptoSupport.c
- The replacement HMAC key as generated in msg/66 was also being
committed into internal memory, replacing the original HMAC key. This
caused the HMAC verification to fail in msg/61 in case TO2 was being
re-tried for the n'th (1-5) time. Instead of re-loading the same at TO2
init, created new methods to separate the current HMAC key and
replacement HMAC key, and only 'commit' replacement HMAC key at msg/70,
if reuse was not triggered (with reuse, it is never initialized). This
allows futher implementations to manage the replacement HMAC key in
their own way (for example, TPM stores different objects files, instead
of replacing the original).
- Move the 'devmod' allocation and key-value pais creation to TO2 init,
from app init. This fixes an issue wherein the 'devmod' was not being
sent in …
> Move new hmac key storage to msg/70 and devmod to TO2 init

- lib/fdo.c
- lib/fdoprotctx.c
- tests/unit/test_protctx.c
- Process RVDELAYSEC to use during subsequent retries as the delay
interval. If no RVDELAY is specified, or if value 0 is specified,
then default delay of '3' seconds is chosen before retrying next
RendezvousDirective, or '120' seconds is chosen before retrying
the RendezvousInfo from the start. Max delay is '3600' seconds.
- Fixing an issue where retry (5 times) was not being done completely
for all RendezvousDirectives. Fixed by returning 'true', if the there
are more RendezvousDirectives to be iterated over, or 'false', if there
are no more RendezvousDirectives left in STATE_TO1 and STATE_TO2
methods. The basic idea is that the intermediate RendezvousDirectives in
the RendezvousInfo would return 'false' in case of failures, and, the
final/leaf RendezvousDirective would return 'true' in …
> Process RVDELAYSEC during retry and update retry scenario

- crypto/openssl/tpm20_ECDSASignRoutines.c
- crypto/openssl/tpm20_Utils.c
- device_modules/fdo_sys/sys_utils_linux.c
- lib/fdoprot.c
- lib/include/util.h
- network/include/rest_interface.h
- network/network_if_linux.c
- network/rest_interface.c
- storage/util.c
- Use fopen in 'wx' mode while writing ownership_transfer file.
- Check whether the received header characters are ASCII before using
them.
- Break out of the endless loop in case the 'sz' becomes more than the
expected 'size' while reading REST header character-by-character.
- Add NULL check before using 'ps' in 'fdo_process_states'.
- Using uint8_t* as buffer type, versus the previous 'void*', to avoid
confusion about the buffer usage.
- Removed 'chmod +x' on file from fdo_sys:exec processing, because
the command is expected to be executed without providing extra
permissions to it.
- Initializing 'TSS2_RC' return code and freeing 'engine' referance as
suggested in the API documentation.
> Add certain checks at various situations and update usage

- tests/unit/test_cryptoSupport.c
- tests/unit/test_hal_os.c
- tests/unit/test_protctx.c
> Fix test-cases: Use fdo_alloc and proper-sized input

- network/rest_interface.c
Change the hard-code value of 512 to a pre-defined MACRO.
> Change hard-coded value to a macro

- crypto/include/tpm20_Utils.h
- docs/tpm.md
- utils/tpm_make_ready_ecdsa.sh
- Remove EC384 curve-based configuration from header file and the
script. Update README for the same.
> Remove unsupported EC384 curve-based parameters

- CMakeLists.txt
- device_modules/fdo_sys/fdo_sys.c
- device_modules/fdo_sys/sys_utils_linux.c
- lib/fdo.c
- Return error on receiving empty array for fdo_sys:exec, that is CBOR
value '80', instead of continuing with it and returning error later.
- Log the received RVDelaySec in RendezvousInfo and log the delays.
- Additionally, add a missed NULL check and few new-lines on logs.
> Return error on empty fdo_sys:exec and few minor updates

- docs/setup.md
- lib/fdo.c
Parse the contents of manufacturer_addr.bin manually for the format
{http,https}://<DNS/IP>:port. The parsing is done as follows with all
the requirements mandatory:
- The transport protocol value will be either `http` or `https`
(case-sensitive). Any other value will result in an error.
- The DNS/IP string's maximum value is 100 characters and must only contain
alphanumeric characters (0-9A-za-z), hyphens (-) and dot (.). First
parsed as IP. If it fails, then treated as DNS.
- The port should be an integer between (1-65535).
- The URL separators are `://` and `:`. These should never be
out-of-place.
NOTE: This does not do a full URL validation as per the URL RFC standards.
> Add more stringent checks for manufacturer_addr.bin

- lib/fdo.c
- lib/prot/to2/msg61.c
- lib/prot/to2/msg70.c
- Create the hash of the received public key in Type 61 and compare it
against the stored hash from DI.
- Replace the hash in the DeviceCredential at Type 70, if resale has
been selected by the Owner.
- Fix an issue with file max_serviceinfo_sz.bin to handle integer
overflow/underflow.
> Compare/save publickey hash in Type 61/70 and fix issue in max_serviceinfo_sz.bin

- crypto/common/fdoHmac.c
- crypto/include/fdoCryptoCommons.h
- lib/credentials_from_file.c
- lib/include/fdoprot.h
- Use 32 byte key for HMAC-SHA256 and 64 byte key for HMAC-SHA384
operations for generation of Device HMAC for OwnershipVoucherHeader,
instead of using constant 32 byte key for both. This is done by updating
the DCHMACSecret to be of 32/64 bytes depending DA as ecdsa256/ecdsa384.
> Use 32/64 byte key as DCHMACSecret based on crypto strength

- README.md
The implementation version v1.0.0 complies to FIDO Device Onboard
Specification, but a note for earlier release was left out in the README
file claiming it to be a preliminary release.
Fixes issue #157 
> Remove disclaimer from README

- device_modules/fdo_sys/fdo_sys.c
- device_modules/fdo_sys/fdo_sys.h
- include/fdomodules.h
- lib/fdotypes.c
- lib/include/fdotypes.h
- lib/prot/to2/msg68.c
- lib/prot/to2/msg69.c
Updating Device ServiceInfo callback method to contain parameters for
handling write operations. Following parameters have been added:
- fdow: Writer to be used for writing ServiceInfo
- has_more: bool value that represents whether the module has some
ServiceInfo to send NOW/immediately (true) or not (false).
- is_more: bool value that represents whether the module has some
ServiceInfo to send in the NEXT iteration/message (true), or not
(false).
- mtu: Maximum length of the ServiceInfo that the module can append.
Module MUST use this information to fit the ServiceInfo to send across
messages by partitioning the same and keeping state information.
The ServiceInfo module implementor needs to maintain the necessary
states and implement functionalities for each 'fdo_sdk_si_type'.
Certain new …
> Updating Device ServiceInfo framework to handle writes

- device_modules/fdo_sys/fdo_sys.c
- device_modules/fdo_sys/fdo_sys_utils.h
- device_modules/fdo_sys/sys_utils_linux.c
Implementation of the keep-alive feature has been added. As a part of
this, following fdo_sys keys have been added/updated:
exec_cb, status_cb, fetch, data and eot. Please refer to fdo_sys
specification for further details.
Additionally, log format in the fdo_sys module has been consistent
per-file.
> Add implementation for fdo_sys keep-alive

- device_modules/fdo_sys/sys_utils_linux.c
- Fixing an issue where the process ID was not being reset upon
fdo_sys:exec completion, leading to rejection/non-execution of subsequent
fdo_sys:exec/exec_cb commands.
> Fix: fdo_sys:exec_cb/exec not working after initial fdo_sys:exec

- docs/linux.md
- docs/tpm.md
Upgrade OpenSSL toolkit version to 1.1.1n
> Upgrade OpenSSL toolkit version to 1.1.1n

- lib/fdonet.c
Multiple curl_easy_cleanup performed without
respective curl_easy_init that caused seg fault.
That is fixed by invoked the init call at
appropriate place inside the loop in resolve_dn.
> Invoke curl_easy_init fix while resolving dn

- network/network_if_linux.c
When curl is not installed in system path and
only at custom path, TO1 fails with hosted RV.
Root cause: This is because of http2 is selected
during negotiation with hosted RV and currently
our CSDK implementation does not support it.
Fix: Configure Client to use http 1.1 with curl
> Fix for custom curl with hosted rv

- lib/fdonet.c
- lib/fdoprotctx.c
- lib/include/fdonet.h
- lib/include/fdoprot.h
- lib/include/fdoprotctx.h
- network/include/network_al.h
- network/include/rest_interface.h
- network/network_if_linux.c
- network/rest_interface.c
- tests/unit/test_fdonet.c
- tests/unit/test_hal_os.c
- tests/unit/test_protctx.c
Older network APIs were using sockets for communication and supported only HTTP1.1 connection. 
Remove socket dependency and move to Curl APIs for network communication.
> Update network APIs to support HTTP2 connection

- docs/cse.md
- docs/linux.md
- docs/tpm.md
- network/network_if_linux.c
- utils/install_openssl_curl.sh
Update steps to build curl with nghttp2 in Readme and installation script
- Add --with-nghttp2 flag to build curl to support HTTP2
- Fix memory leak caused by curl_slist_append()
> Update steps to build curl with nghttp2 and fix memory leak

- device_modules/fdo_sys/fdo_sys.c
Onboarding of device was failing with SVI [exec, exec_cb and fetch] because of returning invalid value.
Fixed SVI by returning correct value.
> SVI [exec, exec_cb and fetch] fix

- device_modules/fdo_sys/fdo_sys.c
- device_modules/fdo_sys/sys_utils_linux.c
SVI instruction was failing when provided with tar files. 
Remove file extension check for exec, exec_cb, and fetch commands.
Update execv to execvp to fetch command path from PATH environment.
> Remove file extension check for SVI instruction

- app/main.c
- docs/cse.md
- docs/linux.md
- docs/tpm.md
- include/fdo.h
- lib/fdo.c
Add "-ip" runtime argument to take input for manufacturer address. 
If -ip not specified, manufacturer_addr.bin file used.
> Add run time argument to take input for manufacturer address

- cmake/cli_input.cmake
- cmake/extension.cmake
- docs/build_conf.md
- lib/include/util.h
- lib/m-string.c
- storage/util.c
Added support to get device serial from system BIOS table. 
linux-client required elevated privileges. Use 'sudo' to execute.
> Add support to get device serial from system BIOS table

- lib/fdonet.c
- lib/fdoprotctx.c
- lib/include/fdoprotctx.h
- network/network_if_linux.c
When using RVByPass, prot_ctx->host_dns was pointing to an invalid value after msg 70. Fixed it by copying host_dns value to prot_ctx->host_dns instead of pointing prot_ctx->host_dns to host_dns.
> Fix onboarding when using RVByPass with SNI

- network/network_if_linux.c
Curl automatically sets it when the request is a POST and the data size is larger than 1024 bytes. Requests with the Expect: 100-Continue header have an increased probability of becoming separated from one another, and hence returning with an error.
It can be disabled by setting the Expect: header to the empty string.
> Disable setting "Expect 100" in request header when request data size is larger than 1024 bytes

- .github/workflows/main.yaml
- docs/build_conf.md
- lib/m-string.c
- storage/util.c
Update get device serial logic
> Update get device serial logic

- docs/tpm.md
Add a note on TPM persistent storage index usages
> Add a note on TPM persistent storage index usages

- docs/cse.md
- docs/linux.md
- docs/tpm.md
- utils/install_openssl_curl.sh
- utils/install_tpm_libs.sh
- utils/install_tpm_libs_rhel.sh
Update OpenSSL version to v3.0.14 and curl version to v8.8.0 
Fix install_tpm_libs.sh script
> Update OpenSSL version to v3.0.14 and curl version to v8.8.0
