Jenkinsfile.yml
Added the smoke test stage to the Jenkinsfile and removed the unused commented code.
<sub>Please squash all the commits into a single commit<sub>
=> Added smoke test stage to the Jenkinsfile

network/include/rest_interface.h
=> Updating REST message buffer size to 9000

lib/credentials_from_file.c, lib/fdo.c, lib/fdoblockio.c, lib/fdocred.c, lib/fdotypes.c, lib/prot/to2/msg61.c, tests/unit/test_fdoblockio.c
- General fixes include adding NULL checks and freeing memory
at certain places in code, that were missed earlier.
=> Fixing few issues reported by Klocwork scans

lib/fdo.c
- Fixing an issue where multiple Rendevous/Owner locations via
RendezvousInfo/RVTO2Addr was not wroking correctly. This also handles
unreachable (yet valid) IP/DNS.
- Additionally, updateing DI for handling unreachable (yet valid) IP/DNS.
=> Fixing issues regarding multiple Rendezvous/Owner addresses

NOTICE
Update NOTICE files as per 3rd party dependencies.
=> Update NOTICE files

crypto/common/fdoKeyExchange.c
=> Update KDF to use bits (not bytes) for lstr

lib/fdo.c, lib/fdotypes.c, lib/include/fdotypes.h, lib/include/util.h, lib/prot/di/msg10.c, lib/prot/di/msg11.c, lib/prot/di/msg12.c, lib/prot/di/msg13.c, lib/prot/to1/msg30.c, lib/prot/to1/msg31.c, lib/prot/to1/msg32.c, lib/prot/to1/msg33.c, lib/prot/to2/msg60.c, lib/prot/to2/msg61.c, lib/prot/to2/msg62.c, lib/prot/to2/msg63.c, lib/prot/to2/msg64.c, lib/prot/to2/msg65.c, lib/prot/to2/msg66.c, lib/prot/to2/msg67.c, lib/prot/to2/msg68.c, lib/prot/to2/msg69.c, lib/prot/to2/msg70.c, lib/prot/to2/msg71.c, storage/util.c
- Added check for protocol state at each message.
- Replaced int with size_t a few method signatures.
- Setting few variables to NULL during their definitions.
=> Fixing as per secure coding guidelines

lib/fdotypes.c, lib/include/fdoblockio.h, lib/include/fdotypes.h, lib/prot/di/msg13.c, lib/prot/to2/msg70.c
=> Log the Client's GUID post DI/TO2

cmake/cli_input.cmake
Enable support for RESALE feature in default build.
=> Enable resale support by default

app/blob.c
- Use 'crypto_hal_random_bytes()', to generate HMAC key for blobs
configuration, instead of rand().
=> Use HAL Random to generate HMAC keys for blob configuration

crypto/common/fdoCryptoCommon.c
=> Make inlcusion of tpm20_util.h conditional

device_modules/fdo_sys/sys_utils_linux.c, lib/fdo.c, lib/fdoprot.c, lib/fdotypes.c, lib/prot/di/msg13.c
=> Change log levels for certain logs

docs/build_conf.md, docs/linux.md, docs/setup.md
=> Update README for changes

crypto/common/fdoAes.c, crypto/openssl/openssl_AESRoutines.c, docs/build_conf.md, docs/security_implications.md, lib/fdotypes.c, lib/include/fdotypes.h
=> Fixing few typos and minor issues

docs/linux.md, docs/tpm.md
=> Update README for RHEL support

docs/tpm.md, utils/install_tpm_libs_rhel.sh
=> Add TPM support on RHEL

lib/fdo.c
Fix multiple owner_to0_rv_blob support for CSDK devices.
=> Fix multiple owner support for CSDK devices.

crypto/common/fdoCryptoCommon.c, crypto/common/fdoKeyExchange.c, crypto/include/fdoCrypto.h, crypto/include/fdoCryptoCtx.h, crypto/openssl/openssl_ECDSAVerifyRoutines.c, device_modules/fdo_sys/fdo_sys.c, device_modules/fdo_sys/sys_utils_linux.c, lib/fdoblockio.c, lib/fdocred.c, lib/fdotypes.c, lib/include/fdoblockio.h, lib/include/fdotypes.h, lib/prot/to2/msg60.c
Fixing minor issues
- Add certain checks at various situations and update usage
- Removed unused code
- Fix memory leaks
=> Fixing minor issues

README.md, docs/setup.md, lib/m-string.c
- Update device serial character limit to 255
- Add device serial information in the setup.md
=> Update device serial character limit to 255

Jenkinsfile.yml
Update Jenkinsfile to copy PRI artifacts from master
=> Update Jenkinsfile to copy PRI artifacts from master

docs/fdo_pri_manufacturer.md
Add a note regarding fdosys issue
=> Add a note regarding fdosys issue

README.md, docs/build_conf.md, docs/fdo_pri_manufacturer.md, docs/introduction.md, docs/linux.md, docs/setup.md, docs/tpm.md
=> Documentation updates

lib/fdonet.c
Updating comments in fdonet.c
Signed-off-by: Davis Benny <davis.benny@intel.com>
=> Updating comments in fdonet.c

lib/fdo.c, lib/fdotypes.c
=> Fix TO when IP is NULL

CMakeLists.txt, lib/include/util.h
Signed-off-by: tajnisha <tajunnisha.n@intel.com>
=> Fix to enable compilation of CSDK in ubuntu 22

data/manufacturer_addr.bin, docs/setup.md, tests/unit/test_credentials.c, tests/unit/test_fdonet.c, tests/unit/test_protctx.c
switch to host.docker.internal
=> switch to host.docker.internal

docs/linux.md, docs/tpm.md
Readme update for installing safestringlib
=> Readme update for installing safestringlib

NOTICE, NOTICES/curl-libcurl-NOTICE
=> Update NOTICE file

lib/fdonet.c, lib/fdoprotctx.c, network/include/network_al.h, network/network_if_linux.c, tests/unit/test_hal_os.c
Add curl support for HTTP connection
=> Add curl support for HTTP connection

network/network_if_linux.c
Update HTTPS connection to use TLS 1.2
=> Update HTTPS connection to use TLS 1.2

docs/linux.md, docs/tpm.md
Signed-off-by: tajnisha <tajunnisha.n@intel.com>
=> Update Curl version as 7.86 in Readme

cmake/blob_path.cmake, docs/setup.md, lib/include/fdoprot.h, lib/include/util.h, network/include/rest_interface.h, network/network_if_linux.c
Increase max message buffer size to 64000
=> Increase max message buffer size to 64000

device_modules/fdo_sys/fdo_sys.c, lib/include/util.h, network/rest_interface.c, storage/util.c
* Replaced unsafe string function
* Enable debug logs for fdo_sys module
=> Replaced unsafe string function

lib/fdotypes.c
Fix TO when IP/RV is empty string
=> Fix TO when IP/RV is empty string

docs/linux.md, docs/tpm.md
Updating the readme with OpenSSL 1.1.1s
=> Updating the readme with openssl 1.1.1s

docs/cse.md, docs/linux.md, docs/tpm.md, utils/install_tpm_libs.sh, utils/install_tpm_libs_rhel.sh
* Update TPM library installation script
* Readme updates
=> Update TPM library installation script

crypto/openssl/openssl_csr.c
=> Fix Klockwork scan finding

docs/tpm.md, utils/install_tpm_libs_rhel.sh, utils/tpm_make_ready_ecdsa.sh
Update TPM library installation script for RHEL and readme update
=> Update TPM library installation script for RHEL and readme update

NOTICE, NOTICES/curl-libcurl, NOTICES/tpm2-tools
Updating NOTICE files for 1.1.5 Release.
=> Updating NOTICE files for 1.1.5 Release

docs/cse.md, docs/linux.md, docs/tpm.md, utils/install_openssl_curl.sh
=> Update curl version to 8.1.2

tests/unit/test_fdonet.c, tests/unit/test_hal_os.c
=> Update unit tests

cmake/cli_input.cmake, cmake/extension.cmake, docs/build_conf.md, network/network_if_linux.c
Disable SNI by default and minor fixes
=> Disable SNI by default and minor fixes

lib/credentials_from_file.c, network/include/rest_interface.h, network/network_if_linux.c, network/rest_interface.c
=> Fix Coverity scan findings

Jenkinsfile.yml
Added v1.2.0 of Safestring Intel Library as the builds were failing on newer versions.
=> Added v1.2.0 of Safestring Intel Library

docs/cse.md, docs/linux.md, docs/tpm.md, utils/install_openssl_curl.sh
Update OpenSSL version to v3.0.12 and curl version to v8.4.0
=> Update OpenSSL version to v3.0.12 and curl version to v8.4.0

storage/util.c
Add input validation in get_device_serial() function
Add const to char *cmd
=> Add input validation in get_device_serial() function

app/main.c, device_modules/fdo_sys/fdo_sys.c, device_modules/fdo_sys/fdo_sys.h, network/network_if_linux.c
Remove unused variables and change log type
=> Refactor fdo_sys code

lib/fdotypes.c
Enable cross device attestation
=> Enable cross device attestation

app/main.c, crypto/include/fdo_crypto_hal.h, crypto/openssl/openssl_crypto_support.c, device_modules/CMakeLists.txt, device_modules/fdo_sim/fdo_sim.c, device_modules/fdo_sim/fdo_sim.h, device_modules/fdo_sim/fdo_sim_command.c, device_modules/fdo_sim/fdo_sim_download.c, device_modules/fdo_sim/fdo_sim_utils.h, device_modules/fdo_sim/sim_utils_linux.c, include/fdomodules.h, lib/fdo.c, lib/fdotypes.c
Implement fdo.download and fdo.command fsim modules.
=> Add fdo-sim support for Client-SDK

device_modules/fdo_sim/fdo_sim.c, device_modules/fdo_sim/fdo_sim.h, device_modules/fdo_sim/fdo_sim_command.c, device_modules/fdo_sim/fdo_sim_download.c
Update FDO SIM APIs to fix CSDK build
=> Fix CSDK build

lib/fdo.c
Added this check to fix client CSE.
=> Add a condition to check DCActive bit only in case to TPM

lib/m-string.c
Update verifying device serial logic
=> Update verifying device serial logic

.github/workflows/main.yaml
Mitigates CVE `GHSA-5xr6-xhww-33m4`
=> Update workflow deps
